apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: tap-pkg-tap-install-values
  namespace: tap-install
spec:
  toNamespace: default

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tap-pkg-tap-install-values
  namespace: default
spec:
  fromNamespace: tap-install