apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tap-upgrade-tekton-pipeline
  labels:
    apps.tanzu.vmware.com/pipeline: test      # (!) required
    workload-intent: tap-custom-sc
spec:
  params:
    - name: source-url                        # (!) required
    - name: source-revision                   # (!) required
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
        steps:
          - name: test
            image: projects.registry.vmware.com/tanzu_adv_eng/ubuntu-carvel-image:05
            script: |-
              apt-get update
              cd `mktemp -d`
              wget -qO- $(params.source-url) | tar xvz
              go run setup.go


