apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: target-project
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: target-project
spec:
  source:
    git:
      url: https://github.com/msrinivasssa/pythontrials.git
      ref:
        branch: main
