apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tap-upgrade
  labels:
    app.kubernetes.io/component: "test"
    app.kubernetes.io/part-of: tap-upgrade
    workload-intent: tap-custom-sc
spec:
  source:
    git:
      url: https://github.com/msrinivasssa/pythontrials.git
      ref:
        branch: main
