apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kapp.k14s.io/change-group: tap-install-rbac
    kapp.k14s.io/change-rule: "delete after deleting tap-install-gitops/app"
    tkg.tanzu.vmware.com/tanzu-package: tap-pkg-install-cluster-role
  name: tap-pkg-install-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tap-pkg-install-cluster-role
subjects:
- kind: ServiceAccount
  name: tap-pkg-install-sa
  namespace: tap-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kapp.k14s.io/change-group: tap-install-rbac
    kapp.k14s.io/change-rule: "delete after deleting tap-install-gitops/app"
    tkg.tanzu.vmware.com/tanzu-package: tap-pkg-install-cluster-role
  name: tap-pkg-install-sa
  namespace: tap-install
